<?php
/**
 * This file is part of Scaleflex Cloudimage
 *
 * @author Alyzeo LTD <info@alyzeo.com>
 * @category Scaleflex
 * @package Scaleflex\Cloudimage
 * @license BSD-3-Clause
 * @copyright Copyright (c) 2021 Cloudimage (https://www.cloudimage.io/)
 */

/** @var Scaleflex\Cloudimage\Block\Tag $block */
if ($block->isInvalidToken()):
    return;
endif;
?>
<script type="text/javascript">
    window.ciEnable = true;
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Scaleflex_Cloudimage/js/product": {}
        }
    }
</script>
