<?php
/**
 * This file is part of Cloudimage Responsive
 *
 * @author Alyzeo LTD <info@alyzeo.com>
 * @category Cloudimage
 * @package Cloudimage\Responsive
 * @license BSD-3-Clause
 * @copyright Copyright (c) 2021 Cloudimage (https://www.cloudimage.io/)
 */

/** @var Cloudimage\Responsive\Block\Tag $block */
if ($block->isInvalidToken()):
    return;
endif;
$config = $block->getConfig();
?>
<?php if ($block->isLazyLoadingActive()): ?>
<!-- Add lazyload library -->
<script>
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.init = false;
</script>
<script src="https://cdn.scaleflex.it/filerobot/js-cloudimage-responsive/lazysizes.min.js"></script>
<?php endif; ?>

<!-- Add js-cloudimage-responsiv library -->
<script src="https://scaleflex.cloudimg.io/v7/plugins/js-cloudimage-responsive/4.7.0-beta.0/plain/js-cloudimage-responsive.min.js?vh=1ee401&func=proxy"></script>

<!-- Initialize cloudimage responsive -->
<script>
window.ciResponsive = new window.CIResponsive({<?= $block->getConfigToString() ?>});
<?php if ($config->isLazyLoading()): ?>
window.lazySizes.init();
<?php endif; ?>
</script>
