<?php
/**
 * This file is part of Scaleflex Cloudimage
 *
 * @author Alyzeo LTD <info@alyzeo.com>
 * @category Scaleflex
 * @package Scaleflex\Cloudimage
 * @license BSD-3-Clause
 * @copyright Copyright (c) 2021 Cloudimage (https://www.cloudimage.io/)
 */

/** @var Scaleflex\Cloudimage\Block\Tag $block */
if ($block->isInvalidToken()):
    return;
endif;
$config = $block->getConfig();
?>
<?php if ($block->isLazyLoadingActive()): ?>
<!-- Add lazyload library -->
<script>
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.init = false;
</script>
<script src="https://cdn.scaleflex.it/filerobot/js-cloudimage-responsive/lazysizes.min.js"></script>
<?php endif; ?>

<!-- Add js-cloudimage-responsiv library -->
<script src="https://cdn.scaleflex.it/plugins/js-cloudimage-responsive/latest/js-cloudimage-responsive.min.js"></script>
<link rel="stylesheet" href="https://cdn.scaleflex.it/plugins/js-cloudimage-responsive/latest/js-cloudimage-responsive.min.css?vh=a076ef&func=proxy"></link>

<!-- Initialize cloudimage responsive -->
<script>
window.ciCName = '<?= $config->getCName() ?>';
window.ciPrerender = <?= $config->getPrerender() == 1 ? 'true' : 'false' ?>;
window.ciRemoveV7 = <?= $config->isRemoveV7() == 1 ? 'true' : 'false' ?>;
window.ciPreUrl = '';

if (window.ciPrerender) {
    if (window.ciCName.length > 0) {
        window.ciPreUrl = '//' + '<?= $config->getCName() ?>/'
    } else {
        window.ciPreUrl = '//' + '<?= $config->getToken() ?>/'
    }

    if (!window.ciRemoveV7) {
        window.ciPreUrl += 'v7/'
    }
}

window.ciResponsive = new window.CIResponsive({<?= $block->getConfigToString() ?>});
<?php if ($config->isLazyLoading()): ?>
window.lazySizes.init();
<?php endif; ?>
</script>
